// client/src/pages/ProfilePage.tsx
import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { gameService } from '../services/api';
import { Loader2, User, Trophy, Target } from 'lucide-react';

export default function ProfilePage() {
  const { username } = useParams();
  const [stats, setStats] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (username) {
      gameService.getUserStats(username)
        .then(setStats)
        .catch(console.error)
        .finally(() => setLoading(false));
    }
  }, [username]);

  if (loading) return <div className="flex justify-center p-20"><Loader2 className="animate-spin text-blue-500" size={48} /></div>;

  if (!stats) return <div className="text-center p-20 text-red-500">User not found</div>;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-8 mb-8 flex flex-col md:flex-row items-center gap-8">
        <div className="w-24 h-24 rounded-full bg-gradient-to-tr from-blue-500 to-teal-500 flex items-center justify-center text-4xl font-bold text-white shadow-lg">
          {stats.user.username.substring(0, 2).toUpperCase()}
        </div>
        <div className="text-center md:text-left">
            <h2 className="text-3xl font-bold mb-2">{stats.user.username}</h2>
            <p className="text-zinc-400 text-sm">Member since {new Date(stats.user.created_at).toLocaleDateString()}</p>
        </div>
        
        <div className="flex-1 flex justify-center md:justify-end gap-8">
            <div className="text-center">
                <div className="text-3xl font-bold text-yellow-500">{stats.points}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wider">Points</div>
            </div>
            <div className="text-center">
                <div className="text-3xl font-bold text-green-500">{stats.wins}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wider">Wins</div>
            </div>
            <div className="text-center">
                <div className="text-3xl font-bold text-orange-500">{stats.streak}</div>
                <div className="text-xs text-zinc-500 uppercase tracking-wider">Streak</div>
            </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl flex items-center gap-4">
            <div className="p-3 bg-blue-500/20 text-blue-500 rounded-lg">
                <Target size={24} />
            </div>
            <div>
                <div className="text-2xl font-bold">{stats.guesses_made > 0 ? Math.round((stats.guesses_correct / stats.guesses_made) * 100) : 0}%</div>
                <div className="text-sm text-zinc-500">Guess Accuracy</div>
            </div>
        </div>
        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl flex items-center gap-4">
            <div className="p-3 bg-teal-500/20 text-teal-500 rounded-lg">
                <User size={24} />
            </div>
            <div>
                <div className="text-2xl font-bold">{stats.guesses_made}</div>
                <div className="text-sm text-zinc-500">Total Guesses</div>
            </div>
        </div>
        <div className="bg-zinc-900 border border-zinc-800 p-6 rounded-xl flex items-center gap-4">
            <div className="p-3 bg-purple-500/20 text-purple-500 rounded-lg">
                <Trophy size={24} />
            </div>
            <div>
                <div className="text-2xl font-bold">{stats.questions_asked}</div>
                <div className="text-sm text-zinc-500">Questions Asked</div>
            </div>
        </div>
      </div>

      <h3 className="text-xl font-bold mb-4">Recent Games</h3>
      <div className="space-y-4">
        {stats.history && stats.history.length > 0 ? (
            stats.history.map((game: any, index: number) => (
                <div key={index} className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl flex justify-between items-center">
                    <div>
                        <div className="font-bold">{game.day.date}</div>
                        <div className="text-sm text-zinc-400">
                             {game.won ? 'Won' : 'Lost'} with {game.guesses_made} guesses
                        </div>
                    </div>
                    <div className={`text-xl font-bold ${game.won ? 'text-green-500' : 'text-red-500'}`}>
                        {game.points} pts
                    </div>
                </div>
            ))
        ) : (
            <div className="text-center text-zinc-500 py-8">No games played yet.</div>
        )}
      </div>
    </div>
  );
}

// client_old/src/pages/ProfilePage.vue
<template>
    <v-container class="profile-container">
        <!-- Profile Section -->
        <v-card class="mt-3 profile-card">
            <v-card-title>{{ user.user.username }}'s Profile</v-card-title>
            <v-card-text>
                <v-row>
                    <v-col cols="12" md="6">
                        <v-text-field label="Username" prepend-icon="mdi-account" v-model="user.user.username"
                            variant="underlined" disabled></v-text-field>
                    </v-col>
                    <v-col cols="12" md="6">
                        <v-text-field label="Account Created" prepend-icon="mdi-calendar" v-model="formattedCreatedAt"
                            variant="underlined" disabled></v-text-field>
                    </v-col>
                </v-row>
            </v-card-text>
        </v-card>

        <!-- Game Stats -->
        <v-card class="mt-3 stats-card">
            <v-card-title>Game Stats</v-card-title>
            <v-card-text>
                <v-row dense>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Total Points</v-card-title>
                            <v-card-text class="stat-value">{{ user.points }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Wins</v-card-title>
                            <v-card-text class="stat-value">{{ user.wins }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Current streak</v-card-title>
                            <v-card-text class="stat-value">{{ user.streak }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Questions Asked</v-card-title>
                            <v-card-text class="stat-value">{{ user.questions_asked }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Correct Questions</v-card-title>
                            <v-card-text class="stat-value">{{ user.questions_correct }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Incorrect Questions</v-card-title>
                            <v-card-text class="stat-value">{{ user.questions_incorrect }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Guesses Made</v-card-title>
                            <v-card-text class="stat-value">{{ user.guesses_made }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Correct Guesses</v-card-title>
                            <v-card-text class="stat-value">{{ user.guesses_correct }}</v-card-text>
                        </v-card>
                    </v-col>
                    <v-col cols="12" md="4">
                        <v-card class="stat-box">
                            <v-card-title class="stat-title">Incorrect Guesses</v-card-title>
                            <v-card-text class="stat-value">{{ user.guesses_incorrect }}</v-card-text>
                        </v-card>
                    </v-col>
                </v-row>
            </v-card-text>
        </v-card>

        <!-- Game History Section -->
        <v-card class="mt-3 history-card">
            <v-card-title>Game History</v-card-title>
            <v-card-text>
                <v-data-table :items="user.history" item-value="id" class="elevation-1">
                    <template v-slot:default>
                        <thead>
                            <tr>
                                <th class="text-left">Date</th>
                                <th class="text-left">Country</th>
                                <th class="text-left">Points</th>
                                <th class="text-left">Questions Asked</th>
                                <th class="text-left">Guesses Made</th>
                                <th class="text-left">Won</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="entry in user.history" :key="entry.id" :class="entry.won ? 'won-row' : 'lost-row'">
                                <td>{{ entry.day.date }}</td>
                                <td>{{ entry.day.country === null? 'N/A': entry.day.country.name }}</td>
                                <td>{{ entry.points }}</td>
                                <td>{{ entry.questions_asked }}</td>
                                <td>{{ entry.guesses_made }}</td>
                                <td>{{ entry.won ? 'Yes' : 'No' }}</td>
                            </tr>
                        </tbody>
                    </template>
                </v-data-table>
            </v-card-text>
        </v-card>
    </v-container>
</template>

<script lang="ts">
import { ref, onMounted, defineComponent, computed } from "vue";
import { useRoute } from "vue-router";
import { apiService, ProfileState } from "../services/api"; // Update with actual API service
import dayjs from "dayjs";

export default defineComponent({
    name: "ProfilePage",
    setup() {
        const route = useRoute();
        const username = ref<string>(
            Array.isArray(route.params.username)
                ? route.params.username[0]
                : route.params.username
        );

        const user = ref<ProfileState>({
            user: {
                username: "",
                created_at: "",
            },
            points: 0,
            streak: 0,
            wins: 0,
            questions_asked: 0,
            questions_correct: 0,
            questions_incorrect: 0,
            guesses_made: 0,
            guesses_correct: 0,
            guesses_incorrect: 0,
            history: [],
        });
        
        const formattedCreatedAt = computed(() => {
            return user.value.user.created_at
                ? dayjs(user.value.user.created_at).format("MMMM D, YYYY")
                : "";
        });

        onMounted(async () => {
            try {
                const resp = await apiService.getUserProfile(username.value);
                user.value = resp.data;
            } catch (error) {
                console.error("Error fetching user data:", error);
            }
        });

        return {
            user,
            formattedCreatedAt
        };
    },
});
</script>

<style scoped>
.profile-container {
    max-width: 1200px;
    margin: auto;
}

.profile-card, .stats-card, .history-card {
    padding: 20px;
}

.stat-box {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 150px;
    text-align: center;
    border-radius: 8px;
    background-color: #1f1f1f;
    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.4);
}

.stat-title {
    font-weight: bold;
    margin-bottom: 10px;
    font-size: 18px;
    opacity: 0.5;
}

.stat-value {
    font-size: 36px;
    font-weight: bold;
}

.elevation-1 {
    box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12);
}
.lost-row {
    background-color: #aa2222;
    color: white;
}

.won-row {
    background-color: #4caf50aa;
    color: white;
}
@media (max-width: 800px) {
    .profile-container {
        padding: 10px;
    }
}
</style>
