// client_old/src/components/MapBox.vue
<template>
  <v-card class="map-box">
    <v-card-title @click="toggleMap" style="cursor: pointer;">
      World Map <v-icon>{{ isMapVisible ? 'mdi-chevron-up' : 'mdi-chevron-down' }}</v-icon>
    </v-card-title>
    <v-expand-transition>
      <div v-show="isMapVisible" class="map-container">
        <l-map ref="mapRef" :zoom="zoom" :min-zoom="minZoom" :max-zoom="maxZoom" :center="center"
          style="height: 500px; width: 100%;">

          <l-geo-json ref="geoJsonRef" :geojson="countriesData" :options-style="styleCountries"
            :options="geoJsonOptions" @geojson-feature-click="onCountryClicked"
            @geojson-feature-mouseover="onCountryMouseOver" @geojson-feature-mouseout="onCountryMouseOut" />
          <v-btn class="reset-btn" @click="resetMap" title="Reset selected countries">
            <span class="mdi mdi-restore" />
          </v-btn>
          <template v-if="gameStore.isGameOver">
            <v-btn class="correct-btn" @click="showCorrect" title="Reset selected countries">
              <span class="mdi mdi-check" />
            </v-btn>
          </template>
        </l-map>

      </div>
    </v-expand-transition>
  </v-card>
</template>

<script lang="ts">
import { LGeoJson, LMap, LTileLayer } from '@vue-leaflet/vue-leaflet';
import type { Feature, Geometry } from 'geojson';
import * as L from 'leaflet';
import { defineComponent, onMounted, ref, watch } from 'vue';
import { useCountrydleStore } from '../stores/countrydle';

import 'leaflet/dist/leaflet.css';

interface FeatureProperties {
  SOVEREIGNT: string;
  // Add other properties if needed
  [key: string]: any;
}

export default defineComponent({
  name: 'MapBox',
  components: {
    LMap,
    LTileLayer,
    LGeoJson,
  },
  setup() {
    const gameStore = useCountrydleStore();

    const geoJsonRef = ref<InstanceType<typeof LGeoJson> | null>(null);
    const mapRef = ref<InstanceType<typeof LMap> | null>(null);
    const zoom = ref(2);
    const minZoom = ref(2);
    const maxZoom = ref(10);
    const center = ref<[number, number]>([20, 0]);
    const isMapVisible = ref(true);
    const toggleMap = () => {
      isMapVisible.value = !isMapVisible.value;
    }
    const countriesData = ref<any>(null);

    const loadCountriesData = async () => {
      try {
        const response = await fetch('/countries_50m.geojson');
        countriesData.value = await response.json();
      } catch (error) {
        console.error('Error loading countries data:', error);
      }
    };

    const isCountryCorrect = (cName: string): boolean => {
      return gameStore.correctCountry !== null && gameStore.correctCountry.name.toUpperCase() === cName.toUpperCase();
    }
    const getCountryColor = (isSelected: boolean, isCorrect: boolean): string => {
      return isCorrect ? '#22cc22' : (isSelected ? '#cc2222' : '#22222')
    }

    const styleCountries = (feature?: Feature<Geometry, FeatureProperties>): L.PathOptions => {
      if (!feature || !feature.properties) {
        return {
          fillColor: '#000000', // Default fill color
          weight: 1,
          opacity: 1,
          color: 'white',
          fillOpacity: 0.7,
        };
      }
      const countryName = feature.properties.SOVEREIGNT;
      const isCorrect = isCountryCorrect(countryName);
      const isSelected = gameStore.selectedCountries.includes(countryName.toUpperCase());
      return {
        fillColor: getCountryColor(isSelected, isCorrect),
        weight: 1,
        opacity: 1,
        color: 'white',
        fillOpacity: 0.7,
      };
    };

    const onCountryClicked = (event: L.LeafletMouseEvent) => {
      const countryName = event.target.feature.properties.SOVEREIGNT.toUpperCase();
      const isSelected = gameStore.handleCountryClick(countryName);
      const isCorrect = isCountryCorrect(countryName);
      if (isCorrect) return;

      if (geoJsonRef.value === null || geoJsonRef.value.leafletObject === undefined) return;
      const lObj = geoJsonRef.value.leafletObject as L.GeoJSON & { _layers: L.Path & { feature?: Feature<Geometry, FeatureProperties> } };
      for (const layer of Object.values(lObj._layers)) {
        const l = layer as L.Path & { feature?: Feature<Geometry, FeatureProperties> };
        if (!l.feature || l.feature.properties.SOVEREIGNT.toUpperCase() !== countryName) continue;
        l.setStyle({
          fillColor: getCountryColor(isSelected, false),
        });
      }

    };

    const onCountryMouseOut = (event: L.LeafletMouseEvent) => {
      const layer = event.target;
      layer.setStyle(styleCountries(layer.feature));
      layer.closeTooltip();
    };

    const onCountryMouseOver = (event: L.LeafletMouseEvent) => {
      const layer = event.target;
      const sovereigntName = layer.feature.properties.SOVEREIGNT; // Adjust property name if needed
      const countryName = layer.feature.properties.ADMIN; // Adjust property name if needed
      let tooltip = `<b>${countryName}</b>`;
      if (sovereigntName !== countryName) tooltip = `<b>${sovereigntName}</b><br/>${countryName}`
      layer.setStyle({
        weight: 2,
        fillOpacity: 0.8,
      });
      layer.bindTooltip(tooltip).openTooltip();
    };

    const geoJsonOptions = {
      style: styleCountries,
      onEachFeature: (_: Feature<Geometry, FeatureProperties>, layer: L.Layer) => {
        layer.on({
          click: onCountryClicked,
          mouseover: onCountryMouseOver,
          mouseout: onCountryMouseOut,
        });
      },
    };

    const resetMap = () => {
      gameStore.selectedCountries = [];
      if (geoJsonRef.value === null || geoJsonRef.value.leafletObject === undefined) return;
      const lObj = geoJsonRef.value.leafletObject as L.GeoJSON & { _layers: L.Path & { feature?: Feature<Geometry, FeatureProperties> } };
      for (const layer of Object.values(lObj._layers)) {
        const l = layer as L.Path & { feature?: Feature<Geometry, FeatureProperties> };
        if (!l.feature) continue;
        l.setStyle({
          fillColor: getCountryColor(false, isCountryCorrect(l.feature.properties.SOVEREIGNT)),
        });
      }

    }

    const showCorrect = () => {
      if (geoJsonRef.value === null || geoJsonRef.value.leafletObject === undefined) return;
      const lObj = geoJsonRef.value.leafletObject as L.GeoJSON & { _layers: L.Path & { feature?: Feature<Geometry, FeatureProperties> } };
      let correctLayer: L.Polygon & { feature?: Feature<Geometry, FeatureProperties> } | null = null;
      for (const layer of Object.values(lObj._layers)) {
        const l = layer as L.Polygon & { feature?: Feature<Geometry, FeatureProperties> };
        if (!l.feature || !isCountryCorrect(l.feature.properties.SOVEREIGNT)) continue;
        l.setStyle({
          fillColor: getCountryColor(false, true),
          weight: 2,
        });
        if (isCountryCorrect(l.feature.properties.ADMIN)) correctLayer = l;
      }
      if(mapRef.value === null || mapRef.value.leafletObject === undefined || correctLayer === null) return;
      mapRef.value.leafletObject.flyToBounds(correctLayer.getBounds(), {
        duration: 2,
      })

    }

    onMounted(() => {
      loadCountriesData();
    });

    watch(() => gameStore.isGameOver, (newVal) => {
      if (!newVal) return;
      showCorrect()
    })

    return {
      geoJsonRef,
      mapRef,
      zoom,
      minZoom,
      maxZoom,
      center,
      geoJsonOptions,
      countriesData,
      isMapVisible,
      gameStore,
      toggleMap,
      styleCountries,
      onCountryClicked,
      onCountryMouseOver,
      onCountryMouseOut,
      resetMap,
      showCorrect,
    };
  },
});
</script>

<style>
@import 'leaflet/dist/leaflet.css';

.map-box {
  height: 100%;
  padding: 20px;
}

.l-map {
  width: 100%;
  height: 100%;
}



*,
*:focus,
*:hover {
  outline: none;
}
</style>

<style>
.correct-btn {
  position: relative;
  padding: 0 !important;
  width: 32px !important;
  height: 32px !important;
  min-width: 10px !important;
  top: 110px;
  left: -21px;
  background-color: white !important;
  color: black !important;
  font-size: 22px !important;
  border: 2px solid rgba(0, 0, 0, 0.3) !important;
  border-radius: 3px !important;
  z-index: 1000;
}

.reset-btn {
  position: relative;
  padding: 0 !important;
  width: 32px !important;
  height: 32px !important;
  min-width: 10px !important;
  top: 80px;
  left: 11px;
  background-color: white !important;
  color: black !important;
  font-size: 22px !important;
  border: 2px solid rgba(0, 0, 0, 0.3) !important;
  border-radius: 3px !important;
  z-index: 1000;
}
</style>

// client/src/components/MapBox.tsx
import { useState, useEffect, useRef } from 'react';
import { MapContainer, TileLayer, GeoJSON, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { useGameStore } from '../stores/gameStore';
import L, { type PathOptions } from 'leaflet';
import type { Feature } from 'geojson';
import { RotateCcw, Check } from 'lucide-react';

interface MapBoxProps {
  correctCountryName?: string;
  className?: string;
}

interface MapControlsProps {
  correctCountryName?: string;
  geoJsonData: any;
  map: L.Map | null;
}

function MapControls({ correctCountryName, geoJsonData, map }: MapControlsProps) {
  const { gameState, clearSelection } = useGameStore();

  const handleZoomToCorrect = () => {
    if (map && correctCountryName && geoJsonData) {
      const correctFeature = geoJsonData.features.find((f: any) => 
        f.properties.SOVEREIGNT.toUpperCase() === correctCountryName.toUpperCase()
      );

      if (correctFeature) {
        const layer = L.geoJSON(correctFeature);
        const bounds = layer.getBounds();
        if (bounds.isValid()) {
            map.flyToBounds(bounds, { duration: 2 });
        }
      }
    }
  };

  return (
    <div 
        className="absolute top-0 left-0 mt-16 md:mt-20 ml-2 md:ml-3 flex flex-col gap-2 z-[1000]"
    >
       <button
          onClick={(e) => {
             e.preventDefault();
             clearSelection();
          }}
          className="bg-zinc-800 text-white p-2 rounded shadow-md hover:bg-zinc-700 transition-colors border border-zinc-600 w-8 h-8 flex items-center justify-center cursor-pointer"
          title="Reset selected countries"
       >
          <RotateCcw size={16} />
       </button>
       
       {gameState?.won && (
         <button
            onClick={(e) => {
                e.preventDefault();
                handleZoomToCorrect();
            }}
            className="bg-green-600 text-white p-2 rounded shadow-md hover:bg-green-700 transition-colors border border-green-500 w-8 h-8 flex items-center justify-center cursor-pointer"
            title="Zoom to correct country"
         >
            <Check size={16} />
         </button>
       )}
    </div>
  );
}

function MapController({ correctCountryName, geoJsonData }: { correctCountryName?: string, geoJsonData: any }) {
  const map = useMap();
  const { gameState } = useGameStore();

  useEffect(() => {
    if (gameState?.won && correctCountryName && geoJsonData) {
      // Find the feature for the correct country
      const correctFeature = geoJsonData.features.find((f: any) => 
        f.properties.SOVEREIGNT.toUpperCase() === correctCountryName.toUpperCase()
      );

      if (correctFeature) {
        const layer = L.geoJSON(correctFeature);
        const bounds = layer.getBounds();
        if (bounds.isValid()) {
            map.flyToBounds(bounds, { duration: 2 });
        }
      }
    }
  }, [gameState?.won, correctCountryName, geoJsonData, map]);

  return null;
}

export default function MapBox({ correctCountryName, className }: MapBoxProps) {
  const [geoJsonData, setGeoJsonData] = useState<any>(null);
  const [map, setMap] = useState<L.Map | null>(null);
  const { selectedEntityNames, toggleEntitySelection, gameState } = useGameStore();
  const geoJsonLayerRef = useRef<L.GeoJSON | null>(null);
  
  useEffect(() => {
    fetch('/countries_50m.geojson')
      .then(res => res.json())
      .then(data => setGeoJsonData(data))
      .catch(err => console.error('Failed to load map data', err));
  }, []);

  const getStyleFromState = (feature: any, currentSelectedNames: string[], currentCorrectName?: string): PathOptions => {
    if (!feature || !feature.properties) return {};

    const countryName = feature.properties.SOVEREIGNT.toUpperCase();
    
    let isCorrect = false;
    if (currentCorrectName) {
        isCorrect = countryName === currentCorrectName.toUpperCase();
    }
    const isSelected = currentSelectedNames.includes(countryName);

    return {
      fillColor: isCorrect ? '#22cc22' : (isSelected ? '#cc2222' : '#242424'),
      weight: 1, // Keep thin border
      opacity: 1,
      color: 'white',
      fillOpacity: 0.7,
    };
  };

  const getStyle = (feature: any) => {
      const { selectedEntityNames, correctEntity } = useGameStore.getState();
      return getStyleFromState(feature, selectedEntityNames, correctEntity?.name);
  }

  // Optimization: Update styles imperatively instead of re-rendering whole map
  useEffect(() => {
    if (geoJsonLayerRef.current) {
        geoJsonLayerRef.current.eachLayer((layer: any) => {
             const feature = layer.feature;
             if (feature) {
                 const { gameState, correctEntity } = useGameStore.getState();
                 const newStyle = getStyleFromState(
                     feature, 
                     selectedEntityNames, 
                      gameState?.won ? correctCountryName || correctEntity?.name : undefined
                 );
                 layer.setStyle(newStyle);
                 
                 // If game over and correct country, bring to front
                 const countryName = feature.properties.SOVEREIGNT.toUpperCase();
                  if (gameState?.won && correctCountryName && (countryName === correctCountryName.toUpperCase())) {
                      layer.bringToFront();
                  }
             }
        });
    }
  }, [selectedEntityNames, gameState?.won, correctCountryName]);

  const onEachFeature = (feature: Feature, layer: L.Layer) => {
    const countryName = feature.properties?.SOVEREIGNT;
    
    // Bind click handler
    layer.on({
      click: () => {
        // Allow selection regardless of game state
        toggleEntitySelection(countryName.toUpperCase());
      },
      mouseover: (e) => {
        const l = e.target;
        l.setStyle({
          weight: 2,
          fillOpacity: 0.8,
        });
        l.bringToFront();
      },
      mouseout: (e) => {
        const l = e.target;
        // Reset to computed style using direct store access
        const { selectedEntityNames: currentSelected, correctEntity } = useGameStore.getState();
        
        const style = getStyleFromState(
            feature, 
            currentSelected, 
            gameState?.won ? correctEntity?.name : undefined
        );
        l.setStyle(style);
      }
    });

    if (feature.properties) {
        layer.bindTooltip(`
          <b>${feature.properties.SOVEREIGNT}</b>
          <br/>
          ${feature.properties.ADMIN === feature.properties.SOVEREIGNT ? '' : `(${feature.properties.ADMIN})`}
          `);
    }
  };

  if (!geoJsonData) {
    return <div className="h-[400px] w-full bg-zinc-900 rounded-xl animate-pulse flex items-center justify-center text-zinc-500">Loading Map...</div>;
  }

  return (
    <div className={`w-full bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden shadow-lg relative z-0 ${className ? className : 'h-[350px] md:h-[500px] mb-4 md:mb-8'}`}>
      <style>{`
        .leaflet-interactive:focus {
            outline: none;
        }
      `}</style>
      <MapContainer 
        center={[20, 0]} 
        zoom={2} 
        style={{ height: '100%', width: '100%', background: '#242424' }}
        minZoom={2}
        maxZoom={10}
        attributionControl={false}
        ref={setMap}
      >
        <TileLayer
            url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
        />
        
        <GeoJSON 
            data={geoJsonData} 
            style={getStyle} 
            onEachFeature={onEachFeature}
            ref={geoJsonLayerRef}
        />
        
        <MapController correctCountryName={correctCountryName} geoJsonData={geoJsonData} />
      </MapContainer>
      <MapControls correctCountryName={correctCountryName} geoJsonData={geoJsonData} map={map} />
    </div>
  );
}
